apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devsecops-ingress
spec:
  rules:
  - host: devsecops.local # Use a custom domain for testing
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            # Routes external traffic to the internal frontend-service
            name: frontend-service 
            port:
              number: 80